export const NIGERIAN_INSTITUTIONS = [
  { shortName: "OAU", name: "Obafemi Awolowo University" },
  { shortName: "UNILAG", name: "University of Lagos" },
  { shortName: "UNIBEN", name: "University of Benin" },
  { shortName: "UI", name: "University of Ibadan" },
  { shortName: "UNILORIN", name: "University of Ilorin" },
  { shortName: "UNIPORT", name: "University of Port Harcourt" },
  { shortName: "UNIABUJA", name: "University of Abuja" },
  { shortName: "FUTMINNA", name: "Federal University of Technology, Minna" },
  { shortName: "FUTO", name: "Federal University of Technology, Owerri" },
  { shortName: "UNIMAID", name: "University of Maiduguri" },
  { shortName: "BUK", name: "Bayero University Kano" },
  { shortName: "UNIUYO", name: "University of Uyo" },
  { shortName: "UNN", name: "University of Nigeria, Nsukka" },
  { shortName: "UNIZIK", name: "Nnamdi Azikiwe University" },
  { shortName: "ESUT", name: "Enugu State University of Science and Technology" },
  { shortName: "LASU", name: "Lagos State University" },
  { shortName: "TASUED", name: "Tai Solarin University of Education" },
  { shortName: "KSU", name: "Kogi State University" },
  { shortName: "RSUST", name: "Rivers State University" },
  { shortName: "FUNAAB", name: "Federal University of Agriculture, Abeokuta" },
  { shortName: "FUD", name: "Federal University, Dutse" },
  { shortName: "FUPRE", name: "Federal University of Petroleum Resources, Effurun" },
  { shortName: "FUOYE", name: "Federal University, Oye-Ekiti" },
  { shortName: "UNIOSUN", name: "Osun State University" },
  { shortName: "KWASU", name: "Kwara State University" },
  { shortName: "ABU", name: "Ahmadu Bello University" },
  { shortName: "OOU", name: "Olabisi Onabanjo University" },
  { shortName: "IMSU", name: "Imo State University" },
  { shortName: "EKSU", name: "Ekiti State University" },
  { shortName: "SLU", name: "Sule Lamido University" },
  { shortName: "ABTU", name: "Abubakar Tafawa Balewa University" },
  { shortName: "FUTA", name: "Federal University of Technology, Akure" },
  { shortName: "UDUSOK", name: "Usmanu Danfodiyo University" },
  { shortName: "MAUTY", name: "Modibbo Adama University of Technology" },
  { shortName: "UNIMAID", name: "University of Maiduguri" },
  { shortName: "BASU", name: "Borno State University" },
  { shortName: "YOSU", name: "Yobe State University" },
  { shortName: "NDA", name: "Nigerian Defence Academy" },
  { shortName: "FRCN", name: "Federal College of Education (Technical), Omoku" },
  { shortName: "ILORIN", name: "Kwara State College of Education" }
] as const;
