-- Seed Nigerian Institutions
INSERT INTO "Institution" ("id", "name", "shortName", "state", "address", "isActive", "createdAt", "updatedAt") VALUES
('inst_oau', 'Obafemi Awolowo University', 'OAU', 'OSUN', 'Ile-Ife, Osun State', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('inst_unilag', 'University of Lagos', 'UNILAG', 'LAGOS', 'Akoka, Yaba, Lagos', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('inst_uniben', 'University of Benin', 'UNIBEN', 'EDO', 'PMB 1154, Benin City, Edo State', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('inst_ui', 'University of Ibadan', 'UI', 'OYO', 'Ibadan, Oyo State', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('inst_unilorin', 'University of Ilorin', 'UNILORIN', 'KWARA', 'Ilorin, Kwara State', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('inst_uniport', 'University of Port Harcourt', 'UNIPORT', 'RIVERS', 'Choba, Port Harcourt, Rivers State', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('inst_uniabuja', 'University of Abuja', 'UNIABUJA', 'FCT', 'Gwagwalada, Abuja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('inst_futminna', 'Federal University of Technology, Minna', 'FUTMINNA', 'NIGER', 'Minna, Niger State', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('inst_futo', 'Federal University of Technology, Owerri', 'FUTO', 'IMO', 'Owerri, Imo State', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('inst_unimaid', 'University of Maiduguri', 'UNIMAID', 'BORNO', 'Maiduguri, Borno State', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('inst_buk', 'Bayero University Kano', 'BUK', 'KANO', 'Kano, Kano State', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('inst_uniuyo', 'University of Uyo', 'UNIUYO', 'AKWA_IBOM', 'Uyo, Akwa Ibom State', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('inst_unn', 'University of Nigeria, Nsukka', 'UNN', 'ENUGU', 'Nsukka, Enugu State', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('inst_unizik', 'Nnamdi Azikiwe University', 'UNIZIK', 'ANAMBRA', 'Awka, Anambra State', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('inst_esut', 'Enugu State University of Science and Technology', 'ESUT', 'ENUGU', 'Enugu, Enugu State', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('inst_lasu', 'Lagos State University', 'LASU', 'LAGOS', 'Ojo, Lagos', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('inst_tasued', 'Tai Solarin University of Education', 'TASUED', 'OGUN', 'Ijagun, Ijebu-Ode, Ogun State', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('inst_ksu', 'Kogi State University', 'KSU', 'KOGI', 'Anyigba, Kogi State', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('inst_rsust', 'Rivers State University', 'RSUST', 'RIVERS', 'Nkpolu, Port Harcourt, Rivers State', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('inst_funaab', 'Federal University of Agriculture, Abeokuta', 'FUNAAB', 'OGUN', 'Abeokuta, Ogun State', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('inst_fud', 'Federal University, Dutse', 'FUD', 'JIGAWA', 'Dutse, Jigawa State', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('inst_fupre', 'Federal University of Petroleum Resources, Effurun', 'FUPRE', 'DELTA', 'Effurun, Delta State', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('inst_fuoye', 'Federal University, Oye-Ekiti', 'FUOYE', 'EKITI', 'Oye-Ekiti, Ekiti State', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('inst_uniosun', 'Osun State University', 'UNIOSUN', 'OSUN', 'Osogbo, Osun State', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('inst_kwasu', 'Kwara State University', 'KWASU', 'KWARA', 'Malete, Kwara State', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('inst_abu', 'Ahmadu Bello University', 'ABU', 'KADUNA', 'Zaria, Kaduna State', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('inst_oou', 'Olabisi Onabanjo University', 'OOU', 'OGUN', 'Ago-Iwoye, Ogun State', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('inst_imsu', 'Imo State University', 'IMSU', 'IMO', 'Owerri, Imo State', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('inst_eksu', 'Ekiti State University', 'EKSU', 'EKITI', 'Ado-Ekiti, Ekiti State', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('inst_slu', 'Sule Lamido University', 'SLU', 'JIGAWA', 'Kafin Hausa, Jigawa State', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('inst_abtu', 'Abubakar Tafawa Balewa University', 'ABTU', 'BAUCHI', 'Bauchi, Bauchi State', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('inst_futa', 'Federal University of Technology, Akure', 'FUTA', 'ONDO', 'Akure, Ondo State', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('inst_udusok', 'Usmanu Danfodiyo University', 'UDUSOK', 'SOKOTO', 'Sokoto, Sokoto State', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('inst_mauty', 'Modibbo Adama University of Technology', 'MAUTY', 'ADAMAWA', 'Yola, Adamawa State', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('inst_basu', 'Borno State University', 'BASE', 'BORNO', 'Maiduguri, Borno State', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('inst_nda', 'Nigerian Defence Academy', 'NDA', 'KADUNA', 'Kaduna, Kaduna State', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
